import { Skill } from '@/types/skill'

// 技能注册表 - 网站展示用的元数据
export const SKILLS_REGISTRY: Skill[] = [
  {
    id: 'warren-buffett',
    name: '沃伦·巴菲特',
    nameEn: 'Warren Buffett',
    tagline: '用价值投资之父的眼光审视每一笔决策',
    taglineEn: 'See every decision through the eyes of the greatest investor',
    description: '基于50年股东信、《滚雪球》传记、伯克希尔年会问答提炼。护城河思维、安全边际、市场先生——用巴菲特的框架分析投资与商业决策。',
    category: 'investment',
    tier: 'free',
    sourcesCount: 50,
    knowledgeCutoff: '2026-04',
    emoji: '💰',
    tags: ['投资', '价值投资', '商业分析', '决策'],
    available: true,
  },
  {
    id: 'charlie-munger',
    name: '查理·芒格',
    nameEn: 'Charlie Munger',
    tagline: '多元思维框架，用逆向思考穿透问题本质',
    taglineEn: 'Multi-disciplinary thinking to cut through complexity',
    description: '基于Poor Charlie\'s Almanack和伯克希尔年会记录提炼。逆向思考、Lollapalooza效应、激励机制分析——芒格式批判性思维工具箱。',
    category: 'investment',
    tier: 'free',
    sourcesCount: 40,
    knowledgeCutoff: '2023-11',
    emoji: '🧠',
    tags: ['思维框架', '逆向思考', '心理学', '投资'],
    available: true,
  },
  {
    id: 'elon-musk',
    name: '埃隆·马斯克',
    nameEn: 'Elon Musk',
    tagline: '第一性原理重新定义可能，极限在哪里？',
    taglineEn: 'First principles thinking to redefine what\'s possible',
    description: '基于SpaceX、Tesla内部资料、传记和访谈提炼。第一性原理、五步算法、垂直整合思维——用马斯克的框架突破既有假设。',
    category: 'tech',
    tier: 'free',
    sourcesCount: 45,
    knowledgeCutoff: '2026-04',
    emoji: '🚀',
    tags: ['创业', '工程思维', '第一性原理', '创新'],
    available: true,
  },
  {
    id: 'steve-jobs',
    name: '史蒂夫·乔布斯',
    nameEn: 'Steve Jobs',
    tagline: '技术与人文的交汇处，创造真正重要的产品',
    taglineEn: 'Where technology meets the humanities',
    description: '基于Walter Isaacson传记、斯坦福演讲、苹果内部资料提炼。聚焦即说不、端到端控制、死亡过滤器——Jobs式产品与决策哲学。',
    category: 'tech',
    tier: 'free',
    sourcesCount: 42,
    knowledgeCutoff: '2011-10',
    emoji: '🍎',
    tags: ['产品', '设计', '创业', '领导力'],
    available: true,
  },
  {
    id: 'naval-ravikant',
    name: '纳瓦尔·拉维坎特',
    nameEn: 'Naval Ravikant',
    tagline: '不出卖时间的前提下，如何创造真正的财富',
    taglineEn: 'Build wealth without selling your time',
    description: '基于Naval播客、How to Get Rich系列和AngelList实践提炼。杠杆四象限、特定知识、欲望审计——Naval式财富与人生哲学。',
    category: 'philosophy',
    tier: 'free',
    sourcesCount: 38,
    knowledgeCutoff: '2026-04',
    emoji: '⚡',
    tags: ['财富', '创业', '人生哲学', '杠杆'],
    available: true,
  },
  {
    id: 'richard-feynman',
    name: '理查德·费曼',
    nameEn: 'Richard Feynman',
    tagline: '说不清楚，就是没真正理解——费曼式验证',
    taglineEn: 'If you can\'t explain it simply, you don\'t understand it',
    description: '基于费曼物理学讲义、传记和挑战者号调查记录提炼。命名≠理解、反自欺原则、具象化思考——费曼式学习与问题验证法。',
    category: 'philosophy',
    tier: 'pro',
    sourcesCount: 40,
    knowledgeCutoff: '1988-02',
    emoji: '⚛️',
    tags: ['学习', '科学思维', '批判性思考', '物理'],
    available: true,
  },
  {
    id: 'nassim-taleb',
    name: '纳西姆·塔勒布',
    nameEn: 'Nassim Taleb',
    tagline: '黑天鹅、反脆弱——在不确定中获益',
    taglineEn: 'Thrive in uncertainty with antifragile thinking',
    description: '基于Incerto五部曲和50+访谈提炼。非对称风险、反脆弱、Skin in the Game——塔勒布式尾部风险与决策框架。',
    category: 'philosophy',
    tier: 'pro',
    sourcesCount: 55,
    knowledgeCutoff: '2026-04',
    emoji: '🦢',
    tags: ['风险', '不确定性', '反脆弱', '哲学'],
    available: true,
  },
  {
    id: 'zhang-yiming',
    name: '张一鸣',
    nameEn: 'Zhang Yiming',
    tagline: '延迟满足感，用系统思维构建千亿级产品',
    taglineEn: 'Delayed gratification and systems thinking at massive scale',
    description: '基于字节跳动内部文化文档、公开演讲和采访提炼。高维投影、Context not Control、逃逸平庸重力——张一鸣的产品与组织思维。',
    category: 'tech',
    tier: 'pro',
    sourcesCount: 35,
    knowledgeCutoff: '2026-04',
    emoji: '🎯',
    tags: ['产品', '组织管理', '创业', '算法思维'],
    available: true,
  },
  {
    id: 'zhang-xuefeng',
    name: '张雪峰',
    nameEn: 'Zhang Xuefeng',
    tagline: '普通家庭的孩子，如何用选择代替努力',
    taglineEn: 'Smart choices over blind effort for ordinary families',
    description: '基于张雪峰公开课、直播和采访提炼。社会筛选论、就业反推教育、阶层现实主义——帮普通家庭做出最优教育与职业决策。',
    category: 'education',
    tier: 'free',
    sourcesCount: 30,
    knowledgeCutoff: '2026-03',
    emoji: '🎓',
    tags: ['教育', '志愿填报', '职业规划', '中国'],
    available: true,
  },
  {
    id: 'donald-trump',
    name: '唐纳德·特朗普',
    nameEn: 'Donald Trump',
    tagline: '一切皆谈判——极端锚定与不可预测的权力',
    taglineEn: 'Everything is negotiation — extreme anchoring and strategic unpredictability',
    description: '基于320KB+原始资料：著作、辩论、幕僚回忆录和重大决策记录提炼。谈判框架、真实夸张、不可预测性策略——特朗普决策逻辑的深度解析。',
    category: 'cn-figure',
    tier: 'pro',
    sourcesCount: 48,
    knowledgeCutoff: '2026-04',
    emoji: '🇺🇸',
    tags: ['谈判', '政治', '商业', '领导力'],
    available: true,
  },
]

export function getSkillById(id: string): Skill | undefined {
  return SKILLS_REGISTRY.find(s => s.id === id)
}

export function getSkillsByCategory(category: string): Skill[] {
  if (category === 'all') return SKILLS_REGISTRY.filter(s => s.available)
  return SKILLS_REGISTRY.filter(s => s.category === category && s.available)
}
